#!/bin/bash

# $1 - application name
# $2 - author
# $3 - activity

SELFDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

mkdir -p $1
cd $1

cp -R ${SELFDIR}/common/files/* ./
${SELFDIR}/android/create $1 $2 $3
${SELFDIR}/pc/create $1 $2 $3
