#!/bin/bash

# $1 - application name
# $2 - author
# $3 - label

NAME=$1
AUTHOR=$2
LABEL=$3
PACKAGE='com.'$2'.'$1

# create directory
mkdir ./android

# saving info to file
touch ./android/appinfo
echo "name:	${NAME}
author:	${AUTHOR}
label:	${LABEL}
package:	${PACKAGE}" > ./android/appinfo

# updating files

SELFDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

PROJDIR="./android/"
cp -R ${SELFDIR}/files/* ./android/
${SELFDIR}/../common/substitute ${PROJDIR} ${NAME} ${AUTHOR} ${LABEL}

# updating android project
android update project -p ./android -t 1 -n $NAME

# making link
ln -s ../../source ./android/jni
