#!/bin/bash

# $1 - device

cd ./android

NAME=$(awk '/name:/ {print $2;}' < ./appinfo)
AUTHOR=$(awk '/author:/ {print $2;}' < ./appinfo)
LABEL=$(awk '/label:/ {print $2;}' < ./appinfo)
PACKAGE=$(awk '/package:/ {print $2;}' < ./appinfo)

echo "uninstall"
adb -s $1 shell pm uninstall $PACKAGE

echo "install"
adb -s $1 install ./bin/${NAME}-debug.apk

echo "run installed application"
adb shell monkey -p $PACKAGE -c android.intent.category.LAUNCHER 1

trap "echo 'force stop'; adb -s $1 shell am force-stop ${PACKAGE}" SIGINT SIGTERM

echo "waiting"
adb -s $1 logcat -s $NAME
