#!/bin/bash

# $1 - folder with files to substitute

# $2 - name
# $3 - author
# $4 - label

# perform substitution
for i in $(find $1 -type f); do \
	sed -i.bak "s/\$NAME/$2/g" $i
	sed -i.bak "s/\$AUTHOR/$3/g" $i
	sed -i.bak "s/\$LABEL/$4/g" $i
	sed -i.bak "s/\$PACKAGE/com.$3.$2/g" $i
done

# remove backup files
rm $(find $1 -type f | grep '.bak$')
