#!/bin/bash

# $1 - application name
# $2 - author
# $3 - header

NAME=$1
AUTHOR=$2
LABEL=$3

BUILD_DIR='desktop'

# creating project directory
mkdir ./$BUILD_DIR

# saving info to file
touch ./$BUILD_DIR/appinfo
echo "name:	${NAME}
author:	${AUTHOR}
label:	${LABEL}" > ./$BUILD_DIR/appinfo

# updating files

SELFDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cp -R ${SELFDIR}/files/* ./$BUILD_DIR/
${SELFDIR}/../common/substitute ./$BUILD_DIR/ ${NAME} ${AUTHOR} ${HEADER}

# making link
ln -s ../source ./$BUILD_DIR/
